/*
 * This file is part of "SAP Commerce Developers Toolset" plugin for IntelliJ IDEA.
 * Copyright (C) 2019-2026 EPAM Systems <hybrisideaplugin@epam.com> and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package sap.commerce.toolset.credentials

import com.intellij.credentialStore.CredentialAttributes
import com.intellij.credentialStore.Credentials
import com.intellij.credentialStore.generateServiceName
import com.intellij.ide.passwordSafe.PasswordSafe

/**
 * Secrets of the plugin, stored under the service name generated by the IntelliJ Platform.
 *
 * The JetBrains Client serves credential requests of a Remote Development backend only for service names of the IntelliJ Platform,
 * requests of any other service name are silently denied with an empty result.
 */
object CxCredentialStore {

    private const val SUBSYSTEM = "SAP CX"

    /**
     * Credentials of the [key], falls back to the [legacyServiceName] of the secrets stored before the service name migration.
     */
    fun get(key: String, legacyServiceName: String): Credentials? = PasswordSafe.instance[attributes(key)]
        ?: PasswordSafe.instance[CredentialAttributes(legacyServiceName)]

    /**
     * Stores credentials of the [key] and removes the secret of the [legacyServiceName], if any.
     */
    fun set(key: String, legacyServiceName: String, credentials: Credentials?) {
        PasswordSafe.instance[attributes(key)] = credentials
        PasswordSafe.instance[CredentialAttributes(legacyServiceName)] = null
    }

    fun serviceName(key: String) = generateServiceName(SUBSYSTEM, key)

    private fun attributes(key: String) = CredentialAttributes(serviceName(key))
}
